baseURL: https://twitter.github.io/
languageCode: en-us
title: Twitter Open Source

# disable taxonomy pages
taxonomies: []

permalinks:
  posts: /:year/:month/:title/

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9
